[QNEBE-666] Fix for cve-2007-4559
QuTech-Delft/qne-adk pull request #53
Opened 2022-12-19 10:30 UTC by QFer

* Fix from https://github.com/QuTech-Delft/qne-adk/pull/51 adjusted to pass the pipe lines
* Added unit tests for the changes
* Completed unit tests for resource_manager

2022-12-29 13:14 UTC, platelminto requested changes

2022-12-29 13:14 UTC, platelminto commented on src/adk/managers/resource_manager.py
> +                def safe_extract(tar: Any, app_src_path: str) -> None:
```suggestion
                def safe_extract(tar: tarfile.TarFile, app_src_path: str) -> None:
```

2022-12-29 13:14 UTC, platelminto commented on src/adk/managers/resource_manager.py
> +from typing import cast, Tuple, List, Any
```suggestion
from typing import cast, Tuple, List
```

2023-01-19 06:52 UTC, QFer commented on src/adk/managers/resource_manager.py
> +                def safe_extract(tar: Any, app_src_path: str) -> None:
Nice catch

2023-01-19 06:52 UTC, QFer commented on src/adk/managers/resource_manager.py
> +from typing import cast, Tuple, List, Any
Removed Any

2023-01-20 09:05 UTC, platelminto approved these changes

2023-01-20 10:06 UTC, merged