[QNEBE-728 Update jsonschema validator
QuTech-Delft/qne-adk pull request #74
Opened 2023-08-11 10:48 UTC by cmvanb

Replace deprecated RefResolver with jsonschema referencing implementation.

2023-08-14 13:50 UTC, QFer approved these changes

2023-08-14 13:50 UTC, QFer commented on setup.py
> +                      "tabulate", "jsonschema>=4.19.0", "referencing", "pyyaml", "typing-extensions",
validating an experiment (qne experiment validate experiment-name) fails.
I get: Unhandled exception: <WrappedReferencingError Unresolvable(ref='file:asset.json')>
It looks like the reference to asset.json in experiment.json schema doesn't work

2023-08-14 13:52 UTC, QFer requested changes
I pressed Approve button by accident. There is 1 comment

2023-09-01 14:29 UTC, bkreynen commented
Looked through the code and the changes look good.
However during testing I am not able to properly install it. I first install the qne adk and then SquidASM. During the SquidASM install I get the following error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic-settings 2.0.3 requires pydantic>=2.0.1, but you have pydantic 1.10.12 which is incompatible.
qne-adk 0.3.0 requires pydantic>=2.1.1, but you have pydantic 1.10.12 which is incompatible.
```

This is due to pinning pydantic to `pydantic>=2.1.1` in the adk, but to `pydantic >=1.8.2, < 2.0` in SquidASM.

I would say resolving it is a separate issue from this PR but it does prevent this issue from being tested.

2023-09-15 09:58 UTC, bkreynen commented
Submitted a PR in SquidASM to fix pydantic there: https://github.com/QuTech-Delft/squidasm/pull/37

2023-10-09 12:59 UTC, QFer approved these changes

2023-10-09 13:00 UTC, QFer commented
Looks good. Squidasm 0.12.1 is released to pypi and installs with qne-adk without errors. Also testen schema validation of an experiment and it worked fine.

2023-10-16 06:45 UTC, merged